### ISSUE TITLE
"Internal server error"

### ISSUE THREAD

**Issue by yude** [iamtakagi/dispotify#8]
[dispotify.iamtakagi.net](https://dispotify.iamtakagi.net) にてログインを試行すると、Spotify の OAuth 認証画面で認証後以下の画面に遷移します。
![2021-07-16_08-05-16_msedge_RZFOwoSan9](https://user-images.githubusercontent.com/14804458/125868738-57bbd5b2-9fe3-40ea-bf5c-93c0db3c6687.png)

**Comment by iamtakagi** [comment]
@yude SpotifyのAPI規定があって、正規APIの審査に通らない限り、登録された25個までのメールアドレス以外使えない仕様とのこと
今のところ、ローカルで建ててもらうしか解決策が無くて、Vercel向けの再設計がいつになるかは未定です。
